version: "3.3"

services:

  cerebro:
    image: dylanmei/cerebro
    container_name: cerbero
    depends_on:
      - elasticsearch
    ports:
      - 9000:9000
    networks:
      - elk

  elasticsearch:
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    environment:
      - cluster.name=unfetter
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    deploy:
      resources:
        limits:
          memory: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es1:/usr/share/elasticsearch/data
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.3
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elk
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    hostname: logstash
    build: ./logstash
    image: 127.0.0.1:5000/logstash
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    
    ports:
        - "5044:5044/tcp"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 2


  analytic-system:
    image: 127.0.0.1:5000/analytic-system
    build: ./analytic-system
    container_name: analytic-system
    links:
     - elasticsearch:elasticsearch
    volumes:
     - "./analytic-system/src:/usr/share/unfetter/src"
    networks:
     - elk

networks:
  elk:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  es1:
    driver: local    
