version: '2.2'

services:

 # Cerebro Elasticsearch client
  
  cerebro:
    image: dylanmei/cerebro
    container_name: cerbero
    depends_on:
      - elasticsearch

    ports:
      - 9000:9000
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.6 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=unfetter
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g    
    volumes:
      - es1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped      

    networks:
      unfetter-network:
        ipv4_address: 10.0.2.3     

  logstash:
    build: ./logstash
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    ports:
      - 5000:5000
      - 3515:3515
      - 3516:3516
      - 3517:3517
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    links:
     - elasticsearch:elasticsearch
    restart: unless-stopped     
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.2     

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200      
    ports:
      - 5601:5601
    links:
    - elasticsearch:elasticsearch
    restart: unless-stopped
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.4
 
  analytic-system:
    build: ./analytic-system
    container_name: analytic-system
    links:
     - elasticsearch:elasticsearch
    volumes:
     - "./analytic-system/src:/usr/share/unfetter/src"
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.5

   
  
networks:
  unfetter-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
        gateway: 10.0.2.1
volumes:
  es1:
    driver: local        